### ISSUE TITLE
Incompatibility with Redis Client

### ISSUE THREAD

**Issue by npnikhil** [puzpuzpuz/cls-rtracer#13]
Hi,

Facing Issues with cls-tracer going out of context and returning id as 'undefined' while using it with redis.
There were some suggestions to use https://github.com/abhiche/cls-redis-patch.
Please let me know if there is any better way to resolve this.

**Comment by puzpuzpuz** [comment]
Are you using the latest version of redis client? It's present there, I'd suggest to try the monkey patching approach that `cls-redis-patch` suggests.

**Comment by npnikhil** [comment]
Thanks, Andrey for the suggestion. Will co-ordinate with `redis` maintainers.
