### ISSUE TITLE
Why `cls-hooked` is peer dependency?

### ISSUE THREAD

**Issue by anshulguleria** [puzpuzpuz/cls-rtracer#18]
IMHO peer dependencies are required if you are building plugins for some library. For example lets say you are building webpack plugin then `webpack` will become your peer dependency.

And some who is using webpack can use use your plugin.

But here I think we only need to use this library `cls-rtracer`, and I am not using `cls-hooked`.

By this logic I think we can add `cls-hooked` under your `dependencies` section from `peerDependencies`.

Any thoughts? 

I can raise a pull request if you guys agree.

**Comment by puzpuzpuz** [comment]
The original intent for having `cls-hooked` as a peer dependency was to allow users to reuse the same version of `cls-hooked` and, potentially to re-use the same namespace. But after some thinking, I agree with you. As sharing `cls-hooked` namespace may break `cls-rtracer`, I don't want to deal with it.

I'm going to convert `cls-hooked` into a regular dependency.

cc @keenondrums as the author of the original peer dep PR

**Comment by keenondrums** [comment]
Guys, it seems like there should be only one cls-hooked instance present. Take a look at [this line](https://github.com/Jeff-Lewis/cls-hooked/blob/master/context.js#L453). With multiple instances of cls-hooked there will be conflicts.

**Comment by puzpuzpuz** [comment]
Thanks for pointing this out @keenondrums. I'll update readme with this info.

Related issues/PRs in `cls-hooked`:
* https://github.com/Jeff-Lewis/cls-hooked/pull/46
* https://github.com/Jeff-Lewis/cls-hooked/issues/25

@anshulguleria feel free to upvote them. Once they're resolved, I can convert `cls-hooked` into regular dependency.

**Comment by anshulguleria** [comment]
Thanks @puzpuzpuz for the explanation. Waiting for them to get merged.

**Comment by puzpuzpuz** [comment]
I'm closing this issue as #28 will remove `cls-hooked` dependency. Feel free to reopen it if you'd like to.
