### ISSUE TITLE
Migrate to core CLS API (AsyncLocalStorage)

### ISSUE THREAD

**Issue by puzpuzpuz** [puzpuzpuz/cls-rtracer#26]
2.0.0 (or an experimental version of the library) could start using `AsyncLocalStorage` instead of `cls-hooked`:
https://nodejs.org/api/async_hooks.html#async_hooks_class_asynclocalstorage

That should be done once `AsyncLocalStorage` is backported to Node.js v12.

**Comment by SimenB** [comment]
You of course know this already, but `AsyncLocalStorage` is available in `v12.17`. Do you have any timeline for when you'll be able to start experimenting with it?

**Comment by puzpuzpuz** [comment]
@SimenB yes, I know about the release. The migration should be pretty straightforward. I'm going to start it this or the next week.

**Comment by puzpuzpuz** [comment]
@SimenB v2.0.0 which based on `AsyncLocalStorage` is now available on npm. Please let me know if you face any issue.

**Comment by SimenB** [comment]
Thank you! We've had some issue losing context in prod using v1 - just upgraded and will report back if it makes any difference 👍

**Comment by puzpuzpuz** [comment]
@SimenB please report the issue if it will remain. I'll do my best to help.

**Comment by SimenB** [comment]
Thanks @puzpuzpuz! Deployed to prod a couple of hours ago, and it's looking good so far! The cases I knew where we lost context seems fixed now. I'll check throughout the week if there are any cases we're missing
