### ISSUE TITLE
Extend support for node > 10.4.0

### ISSUE THREAD

**Issue by fmenis** [puzpuzpuz/cls-rtracer#27]
Is it possible to extend library support for versions greater than 10.4.0?

npm WARN notsup  (current: {"node":"10.18.0","npm":"6.13.4"})
Unsupported engine for cls-rtracer@1.4.0: wanted: {"node":">=8.0.0 - <10.0.0 || >=10.4.0"}

It's a very useful toot, and I'd like to add it to my project!

**Comment by puzpuzpuz** [comment]
@fmenis first of all, thanks for reporting this issue!

`cls-rtracer` supports Node.js versions 10.4.0+, so you can start using it safely. The warning gets logged as for some reasons npm doesn't parse the following engines expression correctly: https://github.com/puzpuzpuz/cls-rtracer/blob/master/package.json#L22

I'll try to fix it and release 1.4.1, but again this should not prevent you from using v1.4.0.

**Comment by puzpuzpuz** [comment]
The fix landed in https://github.com/puzpuzpuz/cls-rtracer/commit/a1b46e7ab9cbd44c29ead388b3fd45e455f27aba and now available in v1.4.1. Feel free to reopen this issue if necessary.

**Comment by fmenis** [comment]
@puzpuzpuz thanks for you quick reply and fix. All looks fine now! Bye
