### ISSUE TITLE
Add typings

### ISSUE THREAD

**Issue by sweepyoface** [puzpuzpuz/cls-rtracer#4]
This seems to be the only library I can find that will allow me to get a request ID from the request object, which I need for [pino-http](https://github.com/pinojs/pino-http) (https://github.com/pinojs/pino-http/issues/63). So I'd love TypeScript support.

**Comment by puzpuzpuz** [comment]
Typings were added recently, but I forgot to include them into the npm artifact. Thanks for reaching out and creating this issue.

I've just published the new release (`1.1.1`) which includes typings.
