### ISSUE TITLE
How to add an optional/custom parameter in the cls-tracer express middleware request

### ISSUE THREAD

**Issue by Gurpindersingh** [puzpuzpuz/cls-rtracer#56]
I want to pass an additional optional parameter as username to trace the HTTP request and log the entries. Currently, I am using rTracer.id() of cls-rtracer npm module in my express application to trace the http request. I would really appreciate if someone can help me to pass 'username' as an optional parameter using cls-tracer module.

From React Application, I am passing username in headers and making http request to node.js application. I want to capture username in express application and pass to my outbound service request(Node.js Micro service). In the Node.js Microservice, I want to trace the incoming request and log using Username

**Comment by puzpuzpuz** [comment]
Hi @Gurpindersingh,

You could use `requestIdFactory` option to provide a custom object as the id:
https://github.com/puzpuzpuz/cls-rtracer#configuration

**Comment by Gurpindersingh** [comment]
Thanks @puzpuzpuz
