### ISSUE TITLE
id generation

### ISSUE THREAD

**Issue by HurricaneDancer** [puzpuzpuz/cls-rtracer#57]
Discovered this lib yesterday and it works perfectly for my needs, the main thing I have an issue with is that it is using uuid v1.Could you please upgrade, or allow us to initialize it with our own generation function?

**Comment by HurricaneDancer** [comment]
Oh, I have just realised it is possible to do this already by passing a requestIdFactory option :)

**Comment by puzpuzpuz** [comment]
> Oh, I have just realised it is possible to do this already by passing a requestIdFactory option :)

Yes, that's the case.
