### ISSUE TITLE
Question about multiple request

### ISSUE THREAD

**Issue by TannerS** [puzpuzpuz/cls-rtracer#65]
This may be a dumb question, but i just wanted to be sure that if a route gets hit by x number of users at the same time (or you know, possibly very close cause we cant always recreate a real world scenario) that the trace ids will be different per question and  its not depended on when u define/initial the library or specific to the folder. 

thank you

**Comment by puzpuzpuz** [comment]
Yes, each HTTP request should get its own unique id.

**Comment by TannerS** [comment]
got it, i assume its per application instance is how this works, a singleton design ? or am I wrong? :)

**Comment by puzpuzpuz** [comment]
The context is bound to each particular HTTP request, not Express instance or anything like that. Of course, if you have multiple Express applications running in the same Node.js process, each of them needs to register the middleware.

**Comment by puzpuzpuz** [comment]
Closing this one since as answered. Feel free to reopen if you have more questions.
