### ISSUE TITLE
add Additional information along with requestId

### ISSUE THREAD

**Issue by softmantk** [puzpuzpuz/cls-rtracer#68]
Hi, this question might be wrong but I want to customise the cls-rtracer with additional feature.

Along with requestId, I also want to pass a custom header value and retrieve it later and may be used in my logger to log the info. with `requestIdFactory`  I could set a requestId. is it possible to save additional information in the same context, let's say some sessionId?  In our application, both are different. Sometimes sessionId might not exist. storing requestId+sessionId as requestId seems not a solution rather feels like a hack.

**Comment by puzpuzpuz** [comment]
`requestIdFactory` supports returning any custom primitive value or object. The idea is that whatever you return from it can be later accessed with a `rTracer.id()` call, so you can store any object with arbitrary fields there and, maybe, even mutate it at a later point.

**Comment by puzpuzpuz** [comment]
Closing this one as the readme is now updated accordingly.
