### ISSUE TITLE
Can you set a unique id?

### ISSUE THREAD

**Issue by TannerS** [puzpuzpuz/cls-rtracer#69]
We have a trace id coming from a third party service and would like to use that one, in that request for the logs in our service that calls it. is that possible? here is an example of what we are hoping for 

```
const rTracer = require('cls-rtracer');

const fakeEndpoint = async (req, res) => {
  const traceIdFromThirdParty = req.traceId;
  
  rTracer.setId(traceIdFromThirdParty);
}
```

**Comment by puzpuzpuz** [comment]
Hi. `requestIdFactory` config param serves exactly this purpose:
```js
const rTracer = require('cls-rtracer');

app.register(rTracer.fastifyPlugin, {
  requestIdFactory: (req) => req.traceId
});

const fakeEndpoint = async (req, res) => {
  console.log('here is my 3rd-party request id: ' + rTracer.id());
};
```

**Comment by TannerS** [comment]
hey @puzpuzpuz , dumb question, this is assuming `app` is the server and your adding it like a middleware? this may not work for us, the server lib we use doesnt allow custom middlewares, is there any other option?

**Comment by TannerS** [comment]
@puzpuzpuz hello, thanks for the reply, and ya we do have a web server but its a custom company made one that doesnt allow injection of middlewares (really stupid i know *crys*), so inthis example, we would need to set the id on an method (now that i look at it, no request at all object just a normal function) then use that trace id rest of the code base that calls the `id` function, if that is able to so with `AsyncLocalStorage`, do you have any examples? thanks !

**Comment by TannerS** [comment]
ok ill look, thank you, ill close this but i may have question in future :) thanks!
